### ISSUE TITLE
travis build and test

### ISSUE THREAD

**Issue by gevahn** [gevahn/libnugrid#4]
@dgasmith I think I am missing something. travis builds the library, but do I also build the tests in the same location, or in a test folder? How do I test that the library installs and links correctly?

**Comment by dgasmith** [comment]
Travis is nice because all it does is execute a series of bash commands. What I would do is build and test your project, record the commands that you used, and simply add them line by line to your `.travis.yml`.

**Comment by gevahn** [comment]
ok, but if I want to install, do I need sudo? or do I just install to someplace I have access to? if so, where will that be?

**Comment by dgasmith** [comment]
You can always install it in the same folder as your repo. It looks like you are using CMake, you can just used the staged version as well.

**Comment by gevahn** [comment]
Travis build successful!
